baseURL = "https://7t.ee/"
languageCode = "zh-CN"
title = "个人网址导航"
theme = "bookmark"
disablePathToLower = true
hasCJKLanguage = true
disableKinds = ['taxonomy', 'term', 'sitemap']
[params]
  useDataUri = true
